/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Activities: typeof import('./src/components/Activities/index.vue')['default']
    AdminCongrats1: typeof import('./src/components/AdminCongrats1/index.vue')['default']
    AnimateButton: typeof import('./src/components/AnimateButton/index.vue')['default']
    BackTop: typeof import('./src/components/BackTop/index.vue')['default']
    Birthdaylayout: typeof import('./src/components/birthdaylayout/index.vue')['default']
    ComButton: typeof import('./src/components/ComButton/index.vue')['default']
    Countdown: typeof import('./src/components/Countdown/index.vue')['default']
    Footer: typeof import('./src/components/Footer/index.vue')['default']
    FrameAvatar: typeof import('./src/components/frameAvatar/index.vue')['default']
    Header: typeof import('./src/components/Header/index.vue')['default']
    Maintitle: typeof import('./src/components/Maintitle/index.vue')['default']
    NBackTop: typeof import('naive-ui')['NBackTop']
    NButton: typeof import('naive-ui')['NButton']
    NCard: typeof import('naive-ui')['NCard']
    NCheckbox: typeof import('naive-ui')['NCheckbox']
    NConfigProvider: typeof import('naive-ui')['NConfigProvider']
    NForm: typeof import('naive-ui')['NForm']
    NFormItem: typeof import('naive-ui')['NFormItem']
    NIcon: typeof import('naive-ui')['NIcon']
    NInput: typeof import('naive-ui')['NInput']
    NMessageProvider: typeof import('naive-ui')['NMessageProvider']
    NModal: typeof import('naive-ui')['NModal']
    NSelect: typeof import('naive-ui')['NSelect']
    NSpace: typeof import('naive-ui')['NSpace']
    NSpin: typeof import('naive-ui')['NSpin']
    NTabPane: typeof import('naive-ui')['NTabPane']
    NTabs: typeof import('naive-ui')['NTabs']
    NText: typeof import('naive-ui')['NText']
    NTimeline: typeof import('naive-ui')['NTimeline']
    NTimelineItem: typeof import('naive-ui')['NTimelineItem']
    NTooltip: typeof import('naive-ui')['NTooltip']
    NUpload: typeof import('naive-ui')['NUpload']
    NUploadDragger: typeof import('naive-ui')['NUploadDragger']
    RenewQRmodal: typeof import('./src/components/RenewQRmodal/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Seeback: typeof import('./src/components/Seeback/index.vue')['default']
    ShowQRbank: typeof import('./src/components/showQRbank/index.vue')['default']
    Supporter: typeof import('./src/components/Supporter/index.vue')['default']
    Timeline: typeof import('./src/components/Timeline/index.vue')['default']
  }
}
