/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AdminCongrats: typeof import('./src/components/AdminCongrats/index.vue')['default']
    App: typeof import('./src/components/AdminCongrats/app.vue')['default']
    Button: typeof import('./src/components/button/index.vue')['default']
    ComButton: typeof import('./src/components/ComButton/index.vue')['default']
    Countdown: typeof import('./src/components/Countdown/index.vue')['default']
    Festival: typeof import('./src/components/Festival/index.vue')['default']
    Footer: typeof import('./src/components/Footer/index.vue')['default']
    Header: typeof import('./src/components/Header/index.vue')['default']
    LogIn: typeof import('./src/components/LogIn/index.vue')['default']
    MainBanner: typeof import('./src/components/MainBanner/index.vue')['default']
    NAvatar: typeof import('naive-ui')['NAvatar']
    NButton: typeof import('naive-ui')['NButton']
    NCard: typeof import('naive-ui')['NCard']
    NConfigProvider: typeof import('naive-ui')['NConfigProvider']
    NDrawer: typeof import('naive-ui')['NDrawer']
    NDrawerContent: typeof import('naive-ui')['NDrawerContent']
    NForm: typeof import('naive-ui')['NForm']
    NFormItem: typeof import('naive-ui')['NFormItem']
    NGrid: typeof import('naive-ui')['NGrid']
    NGridItem: typeof import('naive-ui')['NGridItem']
    NInput: typeof import('naive-ui')['NInput']
    NModal: typeof import('naive-ui')['NModal']
    NSelect: typeof import('naive-ui')['NSelect']
    NSpace: typeof import('naive-ui')['NSpace']
    NSpin: typeof import('naive-ui')['NSpin']
    NTabPane: typeof import('naive-ui')['NTabPane']
    NTabs: typeof import('naive-ui')['NTabs']
    NText: typeof import('naive-ui')['NText']
    NUpload: typeof import('naive-ui')['NUpload']
    NUploadDragger: typeof import('naive-ui')['NUploadDragger']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Seeback: typeof import('./src/components/Seeback/index.vue')['default']
    SignUp: typeof import('./src/components/SignUp/index.vue')['default']
    Step: typeof import('./src/components/Step/index.vue')['default']
    Supporter: typeof import('./src/components/Supporter/index.vue')['default']
  }
}
